name: SixLayerFramework
options:
  bundleIdPrefix: com.sixlayer
  deploymentTarget:
    iOS: "17.0"
    macOS: "15.0"
  xcodeVersion: "16.1"
  swiftVersion: "6.0"
  SWIFT_STRICT_CONCURRENCY: disabled
  CODE_SIGN_STYLE: Automatic
  CODE_SIGNING_REQUIRED: YES
  DEVELOPMENT_TEAM: Y53G7YPJSZ
  developmentTeam: Y53G7YPJSZ
  developmentLanguage: en
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

# Project-level build settings
settings:
  base:
    DEAD_CODE_STRIPPING: YES
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    SWIFT_STRING_CATALOG_SYMBOL_GENERATION: YES
  configs:
    Debug:
      DEAD_CODE_STRIPPING: YES
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      SWIFT_STRING_CATALOG_SYMBOL_GENERATION: YES
    Release:
      DEAD_CODE_STRIPPING: YES
      ENABLE_USER_SCRIPT_SANDBOXING: YES
      SWIFT_STRING_CATALOG_SYMBOL_GENERATION: YES

packages:
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector
    version: 0.9.0

targets:
  # Main framework target - supports both iOS and macOS
  SixLayerFramework:
    type: framework
    platform: [iOS, macOS]
    sources:
      - path: Framework/Sources
        excludes:
          - "**/ExampleHelpers.swift"
          - "**/ExtensibleHintsExample.swift"
      - path: Framework/Resources
        excludes:
          - "**/*.lproj/**"
    resources:
      - path: Framework/Resources/Localizable.xcstrings
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sixlayer.framework
      PRODUCT_MODULE_NAME: SixLayerFramework
      SWIFT_VERSION: "6.0"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) ENABLE_PREVIEWS
      ENABLE_TESTABILITY: YES
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: Y53G7YPJSZ
      developmentTeam: Y53G7YPJSZ
      DEAD_CODE_STRIPPING: YES
      CLANG_ENABLE_MODULE_VERIFIER: YES
      CODE_SIGN_IDENTITY: "Apple Development"
      "CODE_SIGN_IDENTITY[sdk=iphoneos*]": "Apple Development"
      "CODE_SIGN_IDENTITY[sdk=macosx*]": "Apple Development"
    dependencies: []

  # Unit tests - iOS
  SixLayerFrameworkUnitTests_iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Development/Tests/Shared/TestHelpers
      - path: Development/Tests/SixLayerFrameworkUnitTests
        excludes:
          - "**/README.md"
          - "**/CoreDataTestingGuide.md"
          - "ViewInspectorTests/**/CoreDataTestingGuide.md"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sixlayer.framework.unit-tests
      SWIFT_VERSION: "6.0"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) VIEW_INSPECTOR_MAC_FIXED
      SWIFT_STRICT_CONCURRENCY: disabled
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      ENABLE_TESTING_SEARCH_PATHS: YES
      DEVELOPMENT_TEAM: Y53G7YPJSZ
      developmentTeam: Y53G7YPJSZ
    dependencies:
      - target: SixLayerFramework_iOS
      - package: ViewInspector
        product: ViewInspector

  # Unit tests - macOS
  SixLayerFrameworkUnitTests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Development/Tests/Shared/TestHelpers
      - path: Development/Tests/SixLayerFrameworkUnitTests
        excludes:
          - "**/README.md"
          - "**/CoreDataTestingGuide.md"
          - "ViewInspectorTests/**/CoreDataTestingGuide.md"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sixlayer.framework.unit-tests
      SWIFT_VERSION: "6.0"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: $(inherited) VIEW_INSPECTOR_MAC_FIXED
      SWIFT_STRICT_CONCURRENCY: disabled
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      ENABLE_TESTING_SEARCH_PATHS: YES
      DEVELOPMENT_TEAM: Y53G7YPJSZ
      developmentTeam: Y53G7YPJSZ
      DEAD_CODE_STRIPPING: YES
    dependencies:
      - target: SixLayerFramework_macOS
      - package: ViewInspector
        product: ViewInspector

  # Real UI tests - iOS (render views in actual windows)
  # Note: Using bundle.unit-test for now - xcodegen doesn't support bundle.ui-test
  # These tests render views in windows but don't require an app target
  SixLayerFrameworkRealUITests_iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Development/Tests/Shared/TestHelpers
      - path: Development/Tests/SixLayerFrameworkRealUITests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sixlayer.framework.real-ui-tests
      SWIFT_VERSION: "6.0"
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      ENABLE_TESTING_SEARCH_PATHS: YES
      DEVELOPMENT_TEAM: Y53G7YPJSZ
      developmentTeam: Y53G7YPJSZ
    dependencies:
      - target: SixLayerFramework_iOS

  # Real UI tests - macOS (render views in actual windows)
  # Note: Using bundle.unit-test for now - xcodegen doesn't support bundle.ui-test
  # These tests render views in windows but don't require an app target
  SixLayerFrameworkRealUITests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Development/Tests/Shared/TestHelpers
      - path: Development/Tests/SixLayerFrameworkRealUITests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sixlayer.framework.real-ui-tests
      SWIFT_VERSION: "6.0"
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      ENABLE_TESTING_SEARCH_PATHS: YES
      DEVELOPMENT_TEAM: Y53G7YPJSZ
      developmentTeam: Y53G7YPJSZ
      DEAD_CODE_STRIPPING: YES
    dependencies:
      - target: SixLayerFramework_macOS

  # External integration tests - iOS
  SixLayerFrameworkExternalIntegrationTests_iOS:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Development/Tests/Shared/TestHelpers
      - path: Development/Tests/SixLayerFrameworkExternalIntegrationTests
        excludes:
          - "**/README.md"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sixlayer.framework.external-integration-tests
      SWIFT_VERSION: "6.0"
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      ENABLE_TESTING_SEARCH_PATHS: YES
      DEVELOPMENT_TEAM: Y53G7YPJSZ
      developmentTeam: Y53G7YPJSZ
    dependencies:
      - target: SixLayerFramework_iOS

  # External integration tests - macOS
  SixLayerFrameworkExternalIntegrationTests_macOS:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Development/Tests/Shared/TestHelpers
      - path: Development/Tests/SixLayerFrameworkExternalIntegrationTests
        excludes:
          - "**/README.md"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.sixlayer.framework.external-integration-tests
      SWIFT_VERSION: "6.0"
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      ENABLE_TESTING_SEARCH_PATHS: YES
      DEVELOPMENT_TEAM: Y53G7YPJSZ
      developmentTeam: Y53G7YPJSZ
      DEAD_CODE_STRIPPING: YES
    dependencies:
      - target: SixLayerFramework_macOS

schemes:
  SixLayerFramework-iOS:
    build:
      targets:
        SixLayerFramework_iOS: all
    test:
      targets:
        - SixLayerFrameworkUnitTests_iOS
        - SixLayerFrameworkExternalIntegrationTests_iOS
      # UITests excluded by default due to ViewInspector Swift 6 issues
      # Uncomment when ViewInspector is fixed:
      # - SixLayerFrameworkUITests_iOS

  SixLayerFramework-macOS:
    build:
      targets:
        SixLayerFramework_macOS: all
    test:
      targets:
        - SixLayerFrameworkUnitTests_macOS
        - SixLayerFrameworkExternalIntegrationTests_macOS
      # UITests excluded by default due to ViewInspector Swift 6 issues
      # Uncomment when ViewInspector is fixed:
      # - SixLayerFrameworkUITests_macOS

  SixLayerFramework-AllTests-iOS:
    build:
      targets:
        SixLayerFramework_iOS: all
    test:
      targets:
        - SixLayerFrameworkUnitTests_iOS
        - SixLayerFrameworkRealUITests_iOS
        - SixLayerFrameworkExternalIntegrationTests_iOS

  SixLayerFramework-AllTests-macOS:
    build:
      targets:
        SixLayerFramework_macOS: all
    test:
      targets:
        - SixLayerFrameworkUnitTests_macOS
        - SixLayerFrameworkRealUITests_macOS
        - SixLayerFrameworkExternalIntegrationTests_macOS

  SixLayerFramework-UnitTestsOnly-iOS:
    build:
      targets:
        SixLayerFramework_iOS: all
    test:
      targets:
        - SixLayerFrameworkUnitTests_iOS

  SixLayerFramework-UnitTestsOnly-macOS:
    build:
      targets:
        SixLayerFramework_macOS: all
    test:
      targets:
        - SixLayerFrameworkUnitTests_macOS

  # SixLayerFramework-UITestsOnly-iOS:
  #   build:
  #     targets:
  #       SixLayerFramework_iOS: all
  #   test:
  #     targets:
  #       - SixLayerFrameworkUITests_iOS  # TODO: Create real UI tests

  # SixLayerFramework-UITestsOnly-macOS:
  #   build:
  #     targets:
  #       SixLayerFramework_macOS: all
  #   test:
  #     targets:
  #       - SixLayerFrameworkUITests_macOS  # TODO: Create real UI tests

