#!/usr/bin/env python3
"""Regenerate Development/VIEWINSPECTOR_CATEGORY_A_CONSOLIDATED_DEDUP.md for issue #197.

Maps each @Test in ConsolidatedAccessibilityTests.swift to either:
  Dedup:<relative-path-under-ViewInspectorTests>/<testName>
when another ViewInspectorTests source defines the same method name first (sorted path order),
or Excluded with owner @schatt when the name exists only in the consolidated file.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONSOLIDATED = ROOT / (
    "Development/Tests/SixLayerFrameworkUnitTests/ViewInspectorTests/"
    "Features/Accessibility/ConsolidatedAccessibilityTests.swift"
)
VI_ROOT = ROOT / "Development/Tests/SixLayerFrameworkUnitTests/ViewInspectorTests"
OUT = ROOT / "Development/VIEWINSPECTOR_CATEGORY_A_CONSOLIDATED_DEDUP.md"

TEST_RE = re.compile(r"@Test\s+@MainActor\s+func\s+(test[A-Za-z0-9_]+)\s*\(")


def main() -> None:
    consolidated_names = sorted(set(TEST_RE.findall(CONSOLIDATED.read_text(encoding="utf-8"))))
    mapping: dict[str, str] = {}
    for path in sorted(VI_ROOT.rglob("*.swift")):
        if path.name == "ConsolidatedAccessibilityTests.swift":
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        for match in TEST_RE.finditer(text):
            name = match.group(1)
            if name not in mapping:
                rel = path.relative_to(VI_ROOT).as_posix()
                mapping[name] = rel

    lines = [
        "# Category A — ConsolidatedAccessibilityTests deduplication (issue #197)",
        "",
        "**Generated by:** `Development/scripts/generate_category_a_consolidated_dedup.py`",
        "",
        "Each `@Test` in `ConsolidatedAccessibilityTests.swift` either **Dedup**s to the first matching",
        "ViewInspector source under `ViewInspectorTests/` (excluding the consolidated file), or is **Excluded**",
        "when the method name exists only in the consolidated aggregate.",
        "",
        f"**Total rows:** {len(consolidated_names)}",
        "",
        "| Consolidated test | Resolution |",
        "|-------------------|------------|",
    ]
    for name in consolidated_names:
        if name in mapping:
            res = f"Dedup:{mapping[name]}/{name}"
        else:
            res = (
                "Excluded: ConsolidatedAccessibilityTests-only aggregate; "
                "no matching canonical ViewInspector test name | Owner:@schatt"
            )
        lines.append(f"| `{name}` | {res} |")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(consolidated_names)} rows to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
